let sample_input = [
  'hot_tea is prepared',
  'hot_coffee is prepared',
  'black_tea cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
  'green_tea cannot be prepared  -> green_mixture is Not Avaialble',
];

let sufficient_ingredient = [
  'black_tea is prepared',
  'hot_tea is prepared',
  'hot_coffee is prepared',
  'black_coffee is prepared',
  'green_tea is prepared',
];

let insufficient_ingredient = [
  'hot_tea cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
  'black_coffee cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
  'hot_coffee cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
  'black_tea cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
  'green_tea cannot be prepared  -> hot_water is Not Avaialble in sufficient quantity',
];

let unavailable_ingredient = [
  'hot_tea is prepared',
  'hot_coffee is prepared',
  'black_tea is prepared',
  'black_coffee is prepared',
  'green_tea cannot be prepared  -> green_mixture is Not Avaialble',
];

let stressTest = [
  'hot_tea is prepared',
  'hot_coffee is prepared',
  'black_tea is prepared',
  'green_tea is prepared',
  'black_coffee is prepared',
  'A is prepared',
  'B is prepared',
  'C is prepared',
  'D is prepared',
  'E is prepared',
  'F is prepared',
  'G is prepared',
  'H is prepared',
  'I is prepared',
  'J is prepared',
  'K is prepared',
  'L is prepared',
  'M is prepared',
  'N is prepared',
  'O is prepared',
  'P is prepared',
  'Q is prepared',
  'R is prepared',
  'S is prepared',
  'T is prepared',
  'U is prepared',
  'V is prepared',
  'W is prepared',
  'X is prepared',
  'Y is prepared',
  'Z is prepared',
  'a is prepared',
  'b is prepared',
  'c is prepared',
  'd is prepared',
  'e is prepared',
  'f is prepared',
  'g is prepared',
  'h is prepared',
  'i is prepared',
  'j is prepared',
  'k is prepared',
  'l is prepared',
  'm is prepared',
  'n is prepared',
  'o is prepared',
  'p is prepared',
  'q is prepared',
  'r is prepared',
  's is prepared',
  't is prepared',
  'u is prepared',
  'v is prepared',
  'w is prepared',
  'x is prepared',
  'y is prepared',
  'z is prepared',
];

module.exports = {
  sample_input,
  sufficient_ingredient,
  insufficient_ingredient,
  unavailable_ingredient,
  stressTest,
};
